---
- name: Deploy Maven Artifact
  hosts: local
  become: yes

  tasks:
    - name: Create deployment directory
      file:
        path: /opt/deployment
        state: directory
        mode: '0755'

    - name: Copy jar file
      copy:
        src: target/hello-maven-1.0-SNAPSHOT.jar
        dest: /opt/deployment/HelloMaven.jar
